import streamlit as st
import pandas as pd
import json
import os
import socket
from datetime import datetime

# --- INTERNAL IMPORTS ---
from src.orchestrator import run_full_pipeline

# --- CONFIGURATION ---
DROP_DOWN_FILE_PATH = "config/UI_drop_downs.csv" # csv file to define the drop-downs in the UI
BASE_JSON_FOLDER_RAW = "data/raw/raw_json_record" # directory to store the raw json files generated by the UI
BASE_JSON_FOLDER_PROCESSED = "data/processed/processed_json_record" # directory to store the successfully ingested json files

st.set_page_config(page_title="SafeVoice: Human Trafficking Source Reporting", layout="wide")

# --- LOAD DROP-DOWNS FROM CSV ---

@st.cache_data
def load_vocabularies():
    df = pd.DataFrame()
    
    try:
        df = pd.read_csv(DROP_DOWN_FILE_PATH)
    except Exception:
        return pd.DataFrame()

    if not df.empty:
        df.columns = df.columns.str.strip()
        df = df.map(lambda x: x.strip() if isinstance(x, str) else x)
        
    return df

vocab_df = load_vocabularies()

def get_options(column_name):
    if not vocab_df.empty and column_name in vocab_df.columns:
        return vocab_df[column_name].dropna().unique().tolist()
    return []

# --- SIDEBAR ---

with st.sidebar:
    st.header("User Information")
    source_id = st.text_input("Please enter your Source ID here", value="#001")
    #organization = st.selectbox("Organization", ["DPO", "Sanctuary Foundation", "EEPA", "SORD"])
    
    device_ip = socket.gethostbyname(socket.gethostname())
    
    st.divider()
    page = st.radio("Navigation", ["Submit Report", "Manage Reports"])
    
    st.caption(f"Session: {datetime.now().strftime('%H:%M')}")

# --- SUBMIT REPORT SECTION ---

if page == "Submit Report":
    st.title("SafeVoice: Submit a Report")
    st.info("Please enter your **Source ID** (in the left sidebar) first, and then fill the form to submit your report.")

    # SECTION 1: RECORD
    st.subheader("1. Record Details")
    c1, c2, c3 = st.columns(3)
    with c1:
        record_id = st.text_input("Record ID", value=f"#{datetime.now().strftime('%M%S')}")
    with c2:
        date_received = st.date_input("Date Received")
    with c3:
        date_recorded = st.date_input("Date Recorded", value=datetime.now())

    # SECTION 2: VICTIM 
    st.subheader("2. Victim Demographics")
    c5, c6, c7, c8, c9 = st.columns(5)
    with c5:
        victim_id = st.text_input("Victim ID", placeholder="#001")
    with c6:
        num_victims = st.number_input("Number of Victims", min_value=1, step=1)
    with c7:
        nationality = st.selectbox("Nationality", options=get_options("Nationality"))
    with c8:
        gender = st.selectbox("Gender", options=get_options("Gender"))
    with c9:
        age = st.number_input("Age", min_value=0, max_value=100, step=1)

    st.markdown("**Status & Location**")
    c_sit, c_loc = st.columns([1, 3])
    with c_sit:
        situation = st.selectbox("Situation", options=get_options("Situation"))

    with c_loc:
        with st.container(border=True):
            st.markdown("**Current Location**")
            cl1, cl2, cl3 = st.columns(3)
            with cl1:
                current_country = st.selectbox("Country", options=get_options("Country"), key="cl_country")
                current_village = st.text_input("Village", key="cl_village")
            with cl2:
                if str(current_country).strip().lower() == "kenya":
                    current_state = st.selectbox("State / County", options=get_options("State(Counties of Kenya)"), key="cl_state")
                else:
                    current_state = st.text_input("State / Region", key="cl_state_txt")
                current_latitude = st.number_input("Latitude", format="%.6f", key="cl_lat")
            with cl3:
                current_town = st.text_input("Town", key="cl_town")
                current_longitude = st.number_input("Longitude", format="%.6f", key="cl_lon")

    victim_desc = st.text_area("Victim Description", placeholder="Enter non-identifiable details...")

    # SECTION 3: INCIDENT
    st.subheader("3. Movement & Incident")
    incident_id = st.text_input("Incident ID", placeholder="#001")

    # Departure
    with st.expander("Departure Details", expanded=True):
        dp1, dp2, dp3 = st.columns(3)
        with dp1:
            dep_country = st.selectbox("Departure Country", options=get_options("Country"), key="dep_country")
            dep_village = st.text_input("Departure Village", key="dep_village")
            dep_name = st.text_input("Location Name", key="dep_name")
        with dp2:
            if str(dep_country).strip().lower() == "kenya":
                dep_state = st.selectbox("Departure State", options=get_options("State(Counties of Kenya)"), key="dep_state")
            else:
                dep_state = st.text_input("Departure State", key="dep_state_txt")
            dep_lat = st.number_input("Latitude", format="%.6f", key="dep_lat")
            dep_type = st.selectbox("Location Type", options=get_options("Type of location"), key="dep_type")
        with dp3:
            dep_town = st.text_input("Departure Town", key="dep_town")
            dep_lon = st.number_input("Longitude", format="%.6f", key="dep_lon")
        
        dep_desc = st.text_area("Departure Description", key="dep_desc")

    # Destination
    with st.expander("Destination Details", expanded=True):
        dst1, dst2, dst3 = st.columns(3)
        with dst1:
            dest_country = st.selectbox("Destination Country", options=get_options("Country"), key="dest_country")
            dest_village = st.text_input("Destination Village", key="dest_village")
        with dst2:
            if str(dest_country).strip().lower() == "kenya":
                dest_state = st.selectbox("Destination State", options=get_options("State(Counties of Kenya)"), key="dest_state")
            else:
                dest_state = st.text_input("Destination State", key="dest_state_txt")
            dest_lat = st.number_input("Latitude", format="%.6f", key="dest_lat")
            dest_type = st.selectbox("Location Type", options=get_options("Type of location"), key="dest_type")
        with dst3:
            dest_town = st.text_input("Destination Town", key="dest_town")
            dest_lon = st.number_input("Longitude", format="%.6f", key="dest_lon")
        
        dest_desc = st.text_area("Destination Description", key="dest_desc")

    # SECTION 4: TRAFFICKER
    st.subheader("4. Trafficker Information")
    t1, t2, t3 = st.columns(3)
    with t1:
        trafficker_id = st.text_input("Trafficker ID", placeholder="#001")
    with t2:
        trafficker_name = st.text_input("Name/Alias")
    with t3:
        trafficker_nat = st.selectbox("Trafficker Nationality", options=get_options("Nationality"))

    trafficker_desc = st.text_area("Trafficker Description")

    # SECTION 5: PUBLICATION
    st.subheader("5. Publication & Evidence")
    p1, p2, p3 = st.columns(3)
    with p1:
        pub_name = st.text_input("Publication Name")
    with p2:
        pub_link = st.text_input("URL / Link")
    with p3:
        pub_date = st.date_input("Publication Date")

    # SECTION 6: SUBMIT REPORT
    st.markdown("---")
    if st.button("Submit Report", type="primary", width="stretch"):
        timestamp_str = datetime.now().strftime('%Y%m%d_%H%M%S')
        
        source_safe = "".join(x for x in source_id if x.isalnum())
        
        # Define the target raw JSON file directory (per source)
        target_json_dir = os.path.join(BASE_JSON_FOLDER_RAW, source_safe)
        
        os.makedirs(target_json_dir, exist_ok=True)

        # Define the JSON file payload
        full_payload = {
            "metadata": {
                "source_id": source_id,
                #"source_org": organization,
                "device_ip": device_ip,
                "timestamp": datetime.now().isoformat()
            },
            "data": {
                "record": {
                    "record_id": record_id, "source_id": source_id, "date_received": str(date_received)
                },
                "victim": {
                    "victim_id": victim_id, "number_of_victims": num_victims, "nationality": nationality, "gender":gender, "age":age, "situation":situation,
                    "current_location": {
                        "country": current_country, "state": current_state, "town": current_town,  "village":current_village,  "latitude":current_latitude, "longitude":current_longitude,
                    },
                    "description": victim_desc
                },
                "incident": {
                    "incident_id":incident_id,
                    "departure": {"country": dep_country, "state": dep_state, "town": dep_town, "village":dep_village, "name": dep_name, "latitude":dep_lat, "longitude":dep_lon, "type":dep_type, "description": dep_desc},
                    "destination": {"country": dest_country, "state": dest_state, "town": dest_town, "village":dest_village, "latitude":dest_lat, "longitude":dest_lon, "type":dest_type, "description": dest_desc}}
                ,
                "trafficker": {
                    "trafficker_id": trafficker_id, "name": trafficker_name, "nationality": trafficker_nat, "description": trafficker_desc
                },
                "publication": {
                    "name": pub_name, "link": pub_link, "date": str(pub_date)
                }
            }    
            }
        

        # Write the raw JSON file to disk
        json_path = os.path.join(target_json_dir, f"report_{timestamp_str}.json")
        with open(json_path, "w") as f:
            json.dump(full_payload, f, indent=4)
        
        # Trigger the data pipeline
        try:
            st.warning("Report submitted. Triggered data pipeline.")
            # 1. Convert the payload into a flattened DataFrame expected by the data cleaning stage
            df_to_clean = pd.json_normalize([full_payload], sep='_')
            
            # 2. Execute the data pipeline
            result_df, status = run_full_pipeline(df_to_clean, raw_json_path=json_path)

            if status == "Success":
                st.success(f"Pipeline executed successfully! File archived to processed_json/")
            else:
                st.error("Pipeline execution failed. Check logs.")                  
        
        except Exception as e:
            st.error(f"Report ingested, but data pipeline FAILED: {e}")

# --- MANAGE REPORTS SECTION ---
# Read JSON file from os and flatten it to pandas DataFrame and display it in the UI

elif page == "Manage Reports":
    st.title("Report Overview")
    st.info(f"Viewing records for source **{source_id}**")
    
    source_safe = "".join(x for x in source_id if x.isalnum())
    search_path = os.path.join(BASE_JSON_FOLDER_PROCESSED, source_safe) # Check JSON folder
    
    if os.path.exists(search_path):
        files = [f for f in os.listdir(search_path) if f.endswith('.json')]
        
        if files:
            all_data = []
            for f in files:
                file_path = os.path.join(search_path, f)
                try:
                    with open(file_path, 'r') as json_file:
                        data = json.load(json_file)
                        data['source_file'] = f
                        all_data.append(data)
                except json.JSONDecodeError:
                    st.warning(f"Error reading JSON file: {f}. Skipping.")
                    continue

            # Use json_normalize to flatten the nested JSON structure
            # NOTE: The 'data' key contains the main fields, and the 'metadata' contains timestamp and device ip for checkup purpose,
            # source does not need to read metadata fields so they will be removed
            if all_data:
                combined_df = pd.json_normalize(
                    all_data,
                    sep='_',
                )
                # 1. Drop the 'metadata_' columns
                cols_to_drop = [col for col in combined_df.columns if col.startswith('metadata_')]
                combined_df = combined_df.drop(columns=cols_to_drop, errors='ignore')
                
                # 2. Clean up column names by replacing nested separators
                new_columns = {col: col.replace('data_', '') for col in combined_df.columns}
                combined_df = combined_df.rename(columns=new_columns)
                
                st.markdown("### Global Records View")
                
                with st.expander("Filter Records", expanded=False):
                    col_filter1, col_filter2 = st.columns(2)
                    
                    with col_filter1:
                        filter_col = st.selectbox("Filter by Column", ["-- No Filter --"] + list(combined_df.columns))
                    
                    if filter_col != "-- No Filter --":
                        with col_filter2:
                            # Get unique values for the selected column to populate the multiselect
                            unique_vals = combined_df[filter_col].astype(str).unique()
                            selected_vals = st.multiselect(f"Select values for '{filter_col}'", unique_vals)
                        
                        # Apply Filter
                        if selected_vals:
                            combined_df = combined_df[combined_df[filter_col].astype(str).isin(selected_vals)]
                            st.caption(f"Filtered to {len(combined_df)} records.")

                # DISPLAY TABLE (Native Sort enabled)
                st.write(f"**Total Records:** {len(combined_df)}")
                st.dataframe(combined_df, width="stretch")
                
                st.caption("Records are immutable. To correct errors, submit a new report with an updated Record ID.")
            else:
                st.warning("No valid reports found for this user context.")
        else:
            st.warning("No reports found for this user context.")
    else:
        st.warning("No folder exists for this user yet. Submit a report first.")
 